####################################################################################################
#                                                                                                  #
#                     Integration Tests Configuration for FIPS                                     #
#                                                                                                  #
####################################################################################################

jce.manager=com.pingidentity.crypto.BCFIPSJCEManager
certificate.service=com.pingidentity.crypto.BCFIPSCertificateServiceImpl